version: '3.8'

services:
  minecraft_server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "25565:25565"
      - "25575:25575"
    volumes:
      - minecraft:/data
      - ./:/data 